imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
        public: true

    paybas.quicklogin.listener:
        class: paybas\quicklogin\event\listener
        tags:
            - { name: event.listener }
